# Generated by Django 3.2.8 on 2023-11-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fighters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=24)),
                ('initial', models.CharField(blank=True, max_length=1)),
                ('last_name', models.CharField(max_length=24)),
            ],
        ),
    ]
